version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: khaled1234321
      MYSQL_DATABASE: ecommerce_db
    networks:
      - my_network
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

    redis:
    image: redis:latest
    container_name: redis_container
    networks:
      - my_network
    ports:
      - "6379:6379"

  inventory:
    build:
      context: ./inventory_service
    container_name: inventory_service
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:khaled1234321@mysql_container:3306/ecommerce_db
      - JWT_SECRET_KEY=32eaac05fb5a47912771724325e81ddc09c46b63daeec2b62cdb992c134f2298
    networks:
      - my_network
    ports:
      - "5001:5001"
    depends_on:
      mysql:
        condition: service_healthy

  customers:
    build:
      context: ./customers_service
    container_name: customers_service
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:khaled1234321@mysql_container:3306/ecommerce_db
      - JWT_SECRET_KEY=32eaac05fb5a47912771724325e81ddc09c46b63daeec2b62cdb992c134f2298
    networks:
      - my_network
    ports:
      - "5002:5001"
    depends_on:
      mysql:
        condition: service_healthy

  sales:
    build:
      context: ./sales_service
    container_name: sales_service
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:khaled1234321@mysql_container:3306/ecommerce_db
      - JWT_SECRET_KEY=32eaac05fb5a47912771724325e81ddc09c46b63daeec2b62cdb992c134f2298
      - FLASK_ENV=development  # Ensure profiling is enabled in development
    networks:
      - my_network
    ports:
      - "5003:5001"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./sales_service/performance_profiler:/performance_profiler  # Correct mapping
  reviews:
    build:
      context: ./reviews_service
    container_name: reviews_service
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:khaled1234321@mysql_container:3306/ecommerce_db
      - JWT_SECRET_KEY=32eaac05fb5a47912771724325e81ddc09c46b63daeec2b62cdb992c134f2298
      - FLASK_ENV=development  # Ensure profiling is enabled in development
    networks:
      - my_network
    ports:
      - "5004:5002"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
       - ./reviews_service/performance_profiler:/performance_profiler

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
